baseurl = "https://kvantik.com/"
title = "«Квантик» - журнал для любознательных"
languageCode = "ru-ru"
defaultContentLanguage = "ru"

#canonifyurls = true
#metaDataFormat = "toml"

theme = "kvantik"

favicon = "img/icon_256.png"

paginate = 10
paginatePath = "page"

disqusShortname = ""

SectionPagesMenu = "lazy"

[taxonomies]
  author = "authors"
  illustrator = "illustrators"
  issue = "issues"
  rubric = "rubrics"
  
  
[permalinks]
    post = "/:year/:month/:slug/"


[params]
    copyright = "(c) 2012-2021 Квантик, [МЦНМО](http://mccme.ru)"
# counters and validation
    metrika = 42527479 # does not work well, see partial template
    google = "gpnmRBIcASh3f0jqFcHwKTpb3L3N2yC19zi9kxdRF6A"
    yandex = "415534175552468d"
    keywords = "kvantik, квантик, журнал для школьников, занимательная математика"

#    viewMorePostLink = "/blog/"
    author = "Alexander"

#   email = "yourname@example" - Formspree.io
 
    style = "default"

#    about_us = "<p>Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas.</p>"
#    copyright = "Copyright (c) 2015 - 2016, YourCompany; all rights reserved."
#    addresss = """ """

    date_format = "January 2, 2006"
    logo = "img/logo.png"

    # Text for the top menu link, which goes the root URL for the site.
    # Default (if omitted) is "Home".
    home = "Главная"

    # Select a syntax highight.
    # Check the static/css/highlight directory for options.
    highlight = "default"

    # Sidebar social links.
    facebook = "kvantik12"
    youtube = "kvantik12" 



[params.carousel]
    enable = true


[params.testimonials]
    enable = true
    title = "Отзывы"
    subtitle = "We have worked with many clients and we always like to hear they come out from the cooperation happy and satisfied. Have a look what our clients said about us."


[params.widgets]
    categories = true
    tags = true
    search = true

[markup]
  defaultMarkdownHandler = 'blackfriday'
  
[blackfriday]
  angledQuotes = true
  fractions = false

[markup.goldmark.renderer]
unsafe= true
  
[languages]
[languages.ru]
 weight=1
[languages.en]
    weight = 2


