backend:
  name: github
  repo: kvantik/hugo-kvantik
  branch: oldstyle

media_folder: "static/img/uploads" # Media files will be stored in the repo under static/images/uploads
public_folder: "/img/uploads"

publish_mode: editorial_workflow

display_url: http://kvantik.com

collections: # A list of collections the CMS should be able to edit



  - name: "buy-online" # Used in routes, ie.: /admin/collections/:slug/edit
    extension: "yaml"
    label: "Онлайн-магазины"
    label_singular: "онлайн-магазин"
    folder: "data/buy/online" 
    fields:
      - {label: "Заголовок", name: "title", widget: "string"}
      - label: "Список онлайн-магазинов"
        label_singular: "онлайн-магазин"
        name: "store" 
        widget: "list"
        fields:
          - {label: "Название", name: "name", widget: "markdown", required: false}
          - {label: "Продаёт", name: "sells", widget: "markdown", required: false}
          - {label: "Доставка", name: "delivery", widget: "markdown", required: false}
          - {label: "Введите 0, чтобы спрятать с сайта", name: "available", widget: "number", required: false}
          - {label: "Архив: здесь хранится ненужное", name: "dump", widget: "markdown", required: false}

  - name: "buy-retail" # Used in routes, ie.: /admin/collections/:slug/edit
    extension: "yaml"
    label: "Розничные магазины" 
    label_singular: "регион" 
    folder: "data/buy/retail"
    create: true 
    fields:
      - {label: "Заголовок", name: "title", widget: "string"}
      - label: "Список розничных магазинов"
        name: "shops" 
        widget: "list"
        fields:
          - {label: "Название", name: "name", widget: "markdown"}
          - {label: "Контакты", name: "address", widget: "markdown"}
          - {label: "Введите 0, чтобы спрятать с сайта", name: "available", widget: "number"}
          - {label: "Архив: здесь хранится ненужное", name: "dump", widget: "markdown", required: false}
          - label: "Подразделения"
            name: "branches"
            widget: "list"
            required: false
            fields:
              - {label: "Название", name: "name", widget: "markdown"}
              - {label: "Контакты", name: "address", widget: "markdown"}
              - {label: "Введите 1, чтобы отобразить на сайте", name: "available", widget: "number"}
              - {label: "Архив: здесь хранится ненужное", name: "dump", widget: "markdown", required: false}

  - name: "allpages"
    label: "Все страницы"
    editor:
      preview: false
    folder: 'content'
    fields: # The fields each document in this collection have
      - { label: 'Title', name: 'title', widget: 'string' }
      - { label: 'Publish Date', name: 'date', widget: 'datetime' }
      - { label: 'Description', name: 'description', widget: 'string', required: false}
      - { label: 'Body', name: 'body', widget: 'markdown' }

  - label: "Новости" 
    name: "news" # Used in routes, ie.: /admin/collections/:slug/edit
    files:
      - file: "data/news.yaml"
        label: "Файл с новостями"
        name: 'news'
        extension: "yaml"
        create: true 
        fields:
          - label: "Список новостей"
            label_singular: "Новость" 
            name: "news" 
            widget: "list"
            fields:
              - {label: "Содержание", name: "body", widget: "markdown"}
              - {label: "Порядковый номер", name: "number", widget: "number"}
              - {label: "Спрятать с главной?", name: "hide", widget: "boolean", required: false}
              - {label: "Дата", name: "date", widget: "date"}
